const CATEGORY_NTO = 1 // Нестационарные торговые объекты
const CATEGORY_RK = 2 // Рекламные конструкции
const CATEGORY_NTO_OUTLAW = 1011 // Нестационарные торговые объекты (незаконные)
const CATEGORY_RK_OUTLAW = 1012 // Рекламные конструкции (незаконные)
const CATEGORY_OD = 4 // Объекты недвижимости (нежилые)
const CATEGORY_OD_MUNICIPAL = 8 // Муниципальная собственность
const CATEGORY_OD_PRIVATE = 1001 // Частная собственность
const CATEGORY_MKD = 3 // Многоквартирные дома
const CATEGORY_OT = 5 // Общественные территории
const CATEGORY_DT = 7 // Дворовые территории
const CATEGORY_ROAD = 9 // Дороги
const CATEGORY_ARCH = 1002 // Архитектурная подсветка
const CATEGORY_IS = 1004 // Инженерные сети
const CATEGORY_IS_GAS = 1005 // Газификация
const CATEGORY_IS_ELECTRO = 1006 // Электрификация
const CATEGORY_IS_HEAT = 1007 // Теплосети
const CATEGORY_IS_WATERSUP = 1008 // Водоснабжение
const CATEGORY_IS_WATERDIS = 1009 // Водоотведение
const CATEGORY_CONSTRUCT_CAP = 1013 // Объекты капитального строительства
const CATEGORY_PARKING_PAY = 1010 // Платные парковки

const WORK_STATUS_DRAFT = 1 // Черновик
const WORK_STATUS_AGREEMENT_SENT = 4 // Отправлено на согласование
const WORK_STATUS_CONFLICT = 2 // Конфликт

const WORK_FIN_SOURCE_FEDERAL = 1 // Федеральное финансирование
const WORK_FIN_SOURCE_REGIONAL = 2 // Краевое финансирование
const WORK_FIN_SOURCE_LOCAL = 3 // Местное финансирование
const WORK_FIN_SOURCE_OTHER = 4 // Иные источники
const WORK_FIN_SOURCE_OWNER = 5 // Средства собственников

const INCOMING_MESSAGES = 1 // Входящие сообщения

const CATEGORY_FUZZY_SEARCH = {
    [CATEGORY_MKD]: [CATEGORY_MKD],
    [CATEGORY_DT]: [CATEGORY_DT],
    [CATEGORY_OT]: [CATEGORY_OT],
    [CATEGORY_ROAD]: [CATEGORY_ROAD],
    [CATEGORY_ARCH]: [CATEGORY_MKD]
}

const WORK_ATTR_GROUPS = {
    object: {
        active: [CATEGORY_DT, CATEGORY_MKD, CATEGORY_OT, CATEGORY_ROAD, CATEGORY_ARCH]
    },
    description: [CATEGORY_DT, CATEGORY_MKD, CATEGORY_OT, CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS],
    geometry: {
        active: [CATEGORY_DT, CATEGORY_MKD, CATEGORY_OT, CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS],
        edit: [CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS]
    },
    kind: [CATEGORY_DT, CATEGORY_MKD, CATEGORY_OT],
    program: [CATEGORY_ROAD, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS],
    architect: [CATEGORY_ARCH],
    road: [CATEGORY_ROAD],
    landmark: [CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS]
}

const WORK_FIN_SOURCES = {
    [WORK_FIN_SOURCE_FEDERAL]: [CATEGORY_MKD, CATEGORY_OT, CATEGORY_DT, CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS],
    [WORK_FIN_SOURCE_REGIONAL]: [CATEGORY_MKD, CATEGORY_OT, CATEGORY_DT, CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS],
    [WORK_FIN_SOURCE_LOCAL]: [CATEGORY_MKD, CATEGORY_OT, CATEGORY_DT, CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS],
    [WORK_FIN_SOURCE_OTHER]: [CATEGORY_DT, CATEGORY_OT, CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS],
    [WORK_FIN_SOURCE_OWNER]: [CATEGORY_MKD]
}

const EHD_OBJECT_CATEGORIES = [CATEGORY_MKD, CATEGORY_OT, CATEGORY_DT, CATEGORY_ROAD, CATEGORY_ARCH, CATEGORY_IS, CATEGORY_IS_GAS, CATEGORY_IS_ELECTRO, CATEGORY_IS_HEAT, CATEGORY_IS_WATERSUP, CATEGORY_IS_WATERDIS, CATEGORY_OD, CATEGORY_OD_MUNICIPAL, CATEGORY_OD_PRIVATE]

export {
    CATEGORY_NTO,
    CATEGORY_NTO_OUTLAW,
    CATEGORY_RK,
    CATEGORY_RK_OUTLAW,
    CATEGORY_OD,
    CATEGORY_OD_MUNICIPAL,
    CATEGORY_OD_PRIVATE,
    CATEGORY_MKD,
    CATEGORY_OT,
    CATEGORY_DT,
    CATEGORY_ROAD,
    CATEGORY_ARCH,
    CATEGORY_IS,
    CATEGORY_IS_GAS,
    CATEGORY_IS_ELECTRO,
    CATEGORY_IS_HEAT,
    CATEGORY_IS_WATERSUP,
    CATEGORY_IS_WATERDIS,
    CATEGORY_CONSTRUCT_CAP,
    CATEGORY_PARKING_PAY,

    WORK_STATUS_DRAFT,
    WORK_STATUS_AGREEMENT_SENT,
    WORK_STATUS_CONFLICT,

    WORK_FIN_SOURCE_FEDERAL,
    WORK_FIN_SOURCE_REGIONAL,
    WORK_FIN_SOURCE_LOCAL,
    WORK_FIN_SOURCE_OTHER,
    WORK_FIN_SOURCE_OWNER,

    INCOMING_MESSAGES,

    CATEGORY_FUZZY_SEARCH,
    WORK_ATTR_GROUPS,
    WORK_FIN_SOURCES,
    EHD_OBJECT_CATEGORIES
}

export default {
    CATEGORY_NTO: CATEGORY_NTO,
    CATEGORY_NTO_OUTLAW: CATEGORY_NTO_OUTLAW,
    CATEGORY_RK: CATEGORY_RK,
    CATEGORY_RK_OUTLAW: CATEGORY_RK_OUTLAW,
    CATEGORY_OD: CATEGORY_OD,
    CATEGORY_OD_MUNICIPAL: CATEGORY_OD_MUNICIPAL,
    CATEGORY_OD_PRIVATE: CATEGORY_OD_PRIVATE,
    CATEGORY_MKD: CATEGORY_MKD,
    CATEGORY_OT: CATEGORY_OT,
    CATEGORY_DT: CATEGORY_DT,
    CATEGORY_ROAD: CATEGORY_ROAD,
    CATEGORY_ARCH: CATEGORY_ARCH,
    CATEGORY_IS: CATEGORY_IS,
    CATEGORY_IS_GAS: CATEGORY_IS_GAS,
    CATEGORY_IS_ELECTRO: CATEGORY_IS_ELECTRO,
    CATEGORY_IS_HEAT: CATEGORY_IS_HEAT,
    CATEGORY_IS_WATERSUP: CATEGORY_IS_WATERSUP,
    CATEGORY_IS_WATERDIS: CATEGORY_IS_WATERDIS,
    CATEGORY_CONSTRUCT_CAP: CATEGORY_CONSTRUCT_CAP,
    CATEGORY_PARKING_PAY: CATEGORY_PARKING_PAY,

    WORK_STATUS_DRAFT: WORK_STATUS_DRAFT,
    WORK_STATUS_AGREEMENT_SENT: WORK_STATUS_AGREEMENT_SENT,
    WORK_STATUS_CONFLICT: WORK_STATUS_CONFLICT,

    WORK_FIN_SOURCE_FEDERAL: WORK_FIN_SOURCE_FEDERAL,
    WORK_FIN_SOURCE_REGIONAL: WORK_FIN_SOURCE_REGIONAL,
    WORK_FIN_SOURCE_LOCAL: WORK_FIN_SOURCE_LOCAL,
    WORK_FIN_SOURCE_OTHER: WORK_FIN_SOURCE_OTHER,
    WORK_FIN_SOURCE_OWNER: WORK_FIN_SOURCE_OWNER,

    INCOMING_MESSAGES: INCOMING_MESSAGES,

    CATEGORY_FUZZY_SEARCH: CATEGORY_FUZZY_SEARCH,
    WORK_ATTR_GROUPS: WORK_ATTR_GROUPS,
    WORK_FIN_SOURCES: WORK_FIN_SOURCES,
    EHD_OBJECT_CATEGORIES: EHD_OBJECT_CATEGORIES
}
